### ISSUE TITLE
Error when pyenv xontrib loaded

### ISSUE THREAD

**Issue by meramsey** [dyuri/xontrib-langenv#7]
The error when starting shell:
```
usage: source-bash [-h] [-n] [-l] [--envcmd ENVCMD] [--aliascmd ALIASCMD]
                   [--extra-args EXTRA_ARGS] [-u] [-p PREVCMD]
                   [--postcmd POSTCMD] [--funcscmd FUNCSCMD]
                   [--sourcer SOURCER] [--use-tmpfile]
                   [--seterrprevcmd SETERRPREVCMD]
                   [--seterrpostcmd SETERRPOSTCMD] [--overwrite-aliases]
                   [--suppress-skip-message] [--show] [-d]
                   files_or_code [files_or_code ...]

source-bash: error: argument -l/--login: ignored explicit argument 'false'

```

Long form traceback
```
Traceback (most recent call last):
  File "/home/mike/.xonshrc", line 101, in <module>
    xontrib load coreutils distributed output_search docker_tabcomplete autovox pyenv # avox_poetry
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/built_ins.py", line 196, in subproc_captured_hiddenobject
    return xonsh.procs.specs.run_subproc(cmds, captured="hiddenobject", envs=envs)
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/procs/__amalgam__.py", line 3579, in run_subproc
    command.end()
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/procs/__amalgam__.py", line 928, in end
    self._end(tee_output=tee_output)
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/procs/__amalgam__.py", line 936, in _end
    for _ in self.tee_stdout():
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/procs/__amalgam__.py", line 838, in tee_stdout
    for line in self.iterraw():
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/procs/__amalgam__.py", line 725, in iterraw
    proc.wait()
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/procs/__amalgam__.py", line 2626, in wait
    r = self.f(self.args, stdin, stdout, stderr, spec, spec.stack)
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 767, in __call__
    result = dispatch(
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 516, in dispatch
    return _dispatch_func(func, ns)
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 489, in _dispatch_func
    return func(**kwargs)
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 12521, in xontribs_load
    update_context(name, ctx=ctx)
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 12475, in update_context
    modctx = xontrib_context(name)
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 12440, in xontrib_context
    m = importlib.import_module(spec.name)
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xontrib/pyenv.xsh", line 39, in <module>
    source-bash --login=false --interactive=false --suppress-skip-message @(PYENV_PATH) e>/dev/null
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/built_ins.py", line 196, in subproc_captured_hiddenobject
    return xonsh.procs.specs.run_subproc(cmds, captured="hiddenobject", envs=envs)
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/procs/__amalgam__.py", line 3579, in run_subproc
    command.end()
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/procs/__amalgam__.py", line 928, in end
    self._end(tee_output=tee_output)
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/procs/__amalgam__.py", line 936, in _end
    for _ in self.tee_stdout():
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/procs/__amalgam__.py", line 838, in tee_stdout
    for line in self.iterraw():
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/procs/__amalgam__.py", line 725, in iterraw
    proc.wait()
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/procs/__amalgam__.py", line 2626, in wait
    r = self.f(self.args, stdin, stdout, stderr, spec, spec.stack)
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 767, in __call__
    result = dispatch(
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/site-packages/xonsh/__amalgam__.py", line 511, in dispatch
    parsed = parser.parse_args(args)
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/argparse.py", line 1818, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/argparse.py", line 1854, in parse_known_args
    self.error(str(err))
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/argparse.py", line 2575, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/argparse.py", line 2562, in exit
    _sys.exit(status)
SystemExit: 2
Traceback (most recent call last):
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/argparse.py", line 1851, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/argparse.py", line 2060, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/mike/.pyenv/versions/3.9.6/lib/python3.9/argparse.py", line 1982, in consume_optional
    raise ArgumentError(action, msg % explicit_arg)
argparse.ArgumentError: argument -l/--login: ignored explicit argument 'false'
```
My xonshrc:
https://github.com/meramsey/yadm-dotfiles/blob/main/.xonshrc

```
@ xonsh --version
xonsh/0.12.1
~ at 08:33:50
 
@
```

I was on xonsh v11 before with same file. I also uninstalled the legacy one and reinstalled the new one as outlined in
https://github.com/dyuri/xontrib-pyenv

Thanks in advance for your time.

**Comment by dyuri** [comment]
Thanks for reporting this, I've not upgraded yet from v11, gonna check this soon.

**Comment by dyuri** [comment]
Version 1.0.7 released, please check.

**Comment by meramsey** [comment]
> Version 1.0.7 released, please check.

Sweet not seeing an error now. That was amazingly fast thanks for the fix.
